freebsd_instance:
  image: freebsd-12-1-release-amd64

task:
  cpan_cache:
    folder: /perl5
    reupload_on_changes: false # set to false if there is a fingerprint script
    fingerprint_script:
      - echo $CIRRUS_OS 20210109
      
  install_script:
    - sudo pkg install -y p5-App-cpanminus
    - sudo cpanm --installdeps --notest Alien::geos::af
    - sudo cpanm --installdeps .

  script:
    - perl Makefile.PL
    - sudo cpanm --notest --installdeps .
    - make
    - make test

    - echo Dumping alien.json file
    - cat `find blib -name alien.json -print`
    - echo ========
    - echo .la files
    - find blib -name '*.la' -print
