freebsd_instance:
  image: freebsd-12-1-release-amd64

task:
  install_script:
    - sudo pkg install -y p5-App-cpanminus
    - sudo cpanm --installdeps --notest Alien::geos::af

  script:
    - perl Makefile.PL
    - sudo cpanm --installdeps .
    - make
    - make test

    - echo Dumping alien.json file
    - cat `find blib -name alien.json -print`
    - echo ========
    - echo .la files
    - find blib -name '*.la' -print
