language: perl
perl:
  - "5.26"
#  - "5.22"

os:
  - linux
  - osx


sudo: required 

branches:
  except:
    - /appveyor/

cache:
  directories:
    - perl_modules
    - .alienbuild/plugin_fetch_cache
    - Library/Caches/Homebrew
    #- /usr/local


#env:
#  MAKEFLAGS='-j$(nproc)' - nope - exhausts memory

before_install:

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew ls --versions perl > /dev/null || brew install perl; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew outdated perl || brew upgrade perl; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew ls --versions cpanminus > /dev/null || brew install cpanminus; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew outdated cpanminus || brew upgrade cpanminus; fi;

#  make sure we get the brewed perl and cpanm etc
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export PATH=/usr/local/bin:${PATH}; fi;
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then /usr/local/bin/cpanm --version; fi;

#  local::lib target is cached
  #- cpanm --notest local::lib
  #- eval "$(perl -Mlocal::lib=${HOME}/perl5)"
  - cpanm local::lib
  - echo "$(perl -Mlocal::lib=${PWD}/perl_modules)"
  - eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"

  #- cpanm --local-lib=${HOME}/perl5 local::lib && eval $(perl -I ${HOME}/perl5/lib/perl5/ -Mlocal::lib)
  - cpanm --quiet --notest --installdeps .
  

script:
  - eval "$(perl -Mlocal::lib=${PWD}/perl_modules)"
  - export ALIEN_BUILD_PRELOAD=Fetch::Cache
  - perl Makefile.PL
  - make
  - make test
  
  #- echo Dumping alien.json file
  #- cat `find blib -name alien.json -print`
  #- [ "$TRAVIS_OS_NAME" == "osx" ] || echo ========
  #- [ "$TRAVIS_OS_NAME" == "osx" ] || find blib -name '*.la' -print
  #
