---
abstract: 'Alien package for GEOS - Geometry Engine, Open Source'
author:
  - 'Shawn Laffan <shawnlaffan@gmail.com>'
build_requires:
  Alien::Build: '1.41'
  Alien::Build::MM: '1.41'
  Alien::Build::Plugin::Cleanse::BuildDir: '0'
  Alien::MSYS: '0.07'
  Archive::Tar: '0'
  ExtUtils::MakeMaker: '6.52'
  File::Find::Rule: '0'
  HTML::LinkExtor: '0'
  HTTP::Tiny: '0.044'
  IO::Compress::Bzip2: '0'
  IO::Uncompress::Bunzip2: '0'
  PkgConfig: '0.19026'
  Sort::Versions: '0'
  Test::Alien: '0'
  URI: '0'
  URI::Escape: '0'
configure_requires:
  Alien::Build: '1.41'
  Alien::Build::MM: '1.41'
  Alien::Build::Plugin::Cleanse::BuildDir: '0'
  Alien::MSYS: '0'
  ExtUtils::MakeMaker: '6.52'
  PkgConfig: '0'
  Sort::Versions: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Alien-geos
no_index:
  directory:
    - t
    - inc
requires:
  Alien::Base: '1.41'
  Alien::Build: '0.25'
resources:
  bugtracker: https://github.com/shawnlaffan/perl-alien-geos/issues/
  repository: https://github.com/shawnlaffan/perl-alien-geos
version: 1.000_002
x_alienfile:
  generated_by: 'Alien::Build::MM version 1.48'
  requires:
    share:
      Alien::MSYS: '0.07'
      Archive::Tar: '0'
      HTML::LinkExtor: '0'
      HTTP::Tiny: '0.044'
      IO::Compress::Bzip2: '0'
      IO::Uncompress::Bunzip2: '0'
      Sort::Versions: '0'
      URI: '0'
      URI::Escape: '0'
    system: {}
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
